// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2025 witqq contributors

import type { SpreadsheetTheme } from './theme-types';

export const lightTheme: SpreadsheetTheme = {
  name: 'light',
  colors: {
    gridLine: '#e2e2e2',
    background: '#ffffff',
    headerBackground: '#f8f9fa',
    headerText: '#333333',
    headerBorder: '#d0d0d0',
    selectionFill: 'rgba(26, 115, 232, 0.08)',
    selectionBorder: '#1a73e8',
    activeCellBorder: '#1a73e8',
    fillHandle: '#1a73e8',
    cellText: '#1f1f1f',
    cellBorder: '#e2e2e2',
    cellEditBackground: '#ffffff',
    alternateRowBackground: '#f8f9fa',
    hoverRowBackground: '#eef3fc',
    frozenSeparator: '#c0c0c0',
    scrollbarTrack: '#f1f1f1',
    scrollbarThumb: '#c1c1c1',
    scrollbarThumbHover: '#a0a0a0',
    errorBackground: '#fce8e8',
    warningBackground: '#fef3e0',
    changedIndicator: '#1a73e8',
    savedIndicator: '#34a853',
    cellPlaceholder: '#e5e7eb',
  },
  fonts: {
    cell: 'Arial, sans-serif',
    header: 'Arial, sans-serif',
    cellSize: 13,
    headerSize: 13,
  },
  dimensions: {
    rowHeight: 28,
    headerHeight: 32,
    minColumnWidth: 40,
    scrollbarWidth: 14,
    cellPadding: 4,
    borderWidth: 1,
    rowNumberWidth: 50,
  },
  borders: {
    gridLineWidth: 1,
    selectionWidth: 2,
    activeCellWidth: 2,
    frozenPaneWidth: 2,
  },
};

export const darkTheme: SpreadsheetTheme = {
  name: 'dark',
  colors: {
    gridLine: '#3c3c3c',
    background: '#1e1e1e',
    headerBackground: '#2d2d2d',
    headerText: '#cccccc',
    headerBorder: '#404040',
    selectionFill: 'rgba(38, 132, 255, 0.15)',
    selectionBorder: '#2684ff',
    activeCellBorder: '#2684ff',
    fillHandle: '#2684ff',
    cellText: '#d4d4d4',
    cellBorder: '#3c3c3c',
    cellEditBackground: '#2d2d2d',
    alternateRowBackground: '#252525',
    hoverRowBackground: '#2a2d2e',
    frozenSeparator: '#555555',
    scrollbarTrack: '#1e1e1e',
    scrollbarThumb: '#424242',
    scrollbarThumbHover: '#555555',
    errorBackground: '#442222',
    warningBackground: '#443322',
    changedIndicator: '#2684ff',
    savedIndicator: '#3fb950',
    cellPlaceholder: '#3c3c3c',
  },
  fonts: {
    cell: 'Arial, sans-serif',
    header: 'Arial, sans-serif',
    cellSize: 13,
    headerSize: 13,
  },
  dimensions: {
    rowHeight: 28,
    headerHeight: 32,
    minColumnWidth: 40,
    scrollbarWidth: 14,
    cellPadding: 4,
    borderWidth: 1,
    rowNumberWidth: 50,
  },
  borders: {
    gridLineWidth: 1,
    selectionWidth: 2,
    activeCellWidth: 2,
    frozenPaneWidth: 2,
  },
};
